# =========================================================
# fzf Configuration
# =========================================================

if ! command -v fzf >/dev/null 2>&1; then
  return
fi

# Modern fzf integration (Completion & Key-bindings)
# Replaces manual sourcing of Homebrew paths
source <(fzf --zsh)

# Use fd if available for faster file searching
if command -v fd >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="fd --type f --hidden --strip-cwd-prefix $FD_EXCLUDES"
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="fd --type d --hidden --strip-cwd-prefix $FD_EXCLUDES"
fi

# UI & Appearance
export FZF_DEFAULT_OPTS='
  --height=60%
  --layout=reverse
  --border=rounded
  --prompt="  "
  --pointer=" "
  --marker=" "
  --color="header:italic"
  --preview-window=right:65%:wrap:border-left
'

# Preview command using bat if available
if command -v bat >/dev/null 2>&1; then
  export _FZF_PREVIEW_CMD='bat --color=always --style=numbers,changes --line-range=:500 {}'
elif command -v batcat >/dev/null 2>&1; then
  export _FZF_PREVIEW_CMD='batcat --color=always --style=numbers,changes --line-range=:500 {}'
else
  export _FZF_PREVIEW_CMD='cat {}'
fi

export FZF_CTRL_T_OPTS="--preview '$_FZF_PREVIEW_CMD'"

# --- Custom Widgets ---

# Ctrl+F: file picker excluding hidden files
_fzf_file_no_hidden() {
  local cmd result
  if command -v fd >/dev/null 2>&1; then
    cmd="fd --type f --strip-cwd-prefix $FD_EXCLUDES"
  else
    cmd="find . -maxdepth 4 -type f"
  fi
  
  result=$(eval "$cmd" | fzf --preview "$_FZF_PREVIEW_CMD")
  if [[ -n "$result" ]]; then
    LBUFFER+="${(q)result} "
  fi
  zle reset-prompt
}

zle -N _fzf_file_no_hidden
bindkey '^f' _fzf_file_no_hidden

# --- Mac Option Key Patches ---
# Maps the special characters generated by the Mac Option key to fzf widgets.
# This ensures Option+C/T/F work regardless of terminal emulator settings.
typeset -A mac_fzf_map=(
  'ç' fzf-cd-widget       # Option+C
  '†' fzf-file-widget     # Option+T
  'ƒ' _fzf_file_no_hidden # Option+F
)

for key widget in ${(kv)mac_fzf_map}; do
  bindkey "$key" "$widget"
done
